spring.application.name=shared-expenses-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shared_expenses
spring.datasource.username=shared_user
spring.datasource.password=shared_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true